### ISSUE TITLE
Shape cannot match the size during training

### ISSUE THREAD

**Issue by cqbu** [henghuiding/MeViS#3]
During the training, in the part of backbone, I got this error:

 File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 694, in forward
    value = value.reshape(B, self.num_heads, self.value_channels//self.num_heads, n_l)
RuntimeError: shape '[24, 1, 96, 40]' is invalid for input of size 368640

this happened in the part of SpatialImageLanguageAttention, I found num_heads is 1, so this is not a MultiheadAttention right? 
but I don't know whether the shape or the size is wrong, so what is the expected shape or size?

and the full error message is below:
Traceback (most recent call last):
  File "train_net_lmpm.py", line 318, in <module>
    launch(
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/root/MeViS/train_net_lmpm.py", line 312, in main
    return trainer.train()
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 494, in run_step
    loss_dict = self.model(data)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MeViS/lmpm/lmpm_model.py", line 281, in forward
    return self.train_model(batched_inputs)
  File "/root/MeViS/lmpm/lmpm_model.py", line 312, in train_model
    features = self.backbone(images.tensor, lang_feat_sentence, lang_mask)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 785, in forward
    y = super().forward(x, l, l_mask)
  File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 470, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww, l, l_mask)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 590, in forward
    x_residual = self.fusion(x, l, l_mask)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 627, in forward
    lang = self.image_lang_att(x, l, l_mask)  # (B, H*W, dim)
  File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 694, in forward
    value = value.reshape(B, self.num_heads, self.value_channels//self.num_heads, n_l)
RuntimeError: shape '[24, 1, 96, 40]' is invalid for input of size 368640

**Comment by cqbu** [comment]
btw, I found when we call build_batch_data_loader, the parameter ‘prefetch_factor’ is not given, but in detectron2, the default value of prefetch_factor is None, which leads to error in DataLoader of torch when running assert prefetch_factor > 0， because prefetch_factor here is None but 0 is int.

**Comment by heshuting555** [comment]
You can try to use 2 gpus to run! And the error will go away!

**Comment by cilinyan** [comment]
> You can try to use multiple gpus to run! And the error will go away!

The reason for this issue is the incorrect use of repeat dimensions in some places, such as [this](https://github.com/henghuiding/MeViS/blob/bec2abd1cdc692fe4c2e236bc0117fe0512cc254/lmpm/lmpm_model.py#L309-L310). 
One simple approach is to ensure that only one video is trained on each GPU. 
Alternatively, you can fix those errors in the code, with [this](https://github.com/henghuiding/MeViS/blob/bec2abd1cdc692fe4c2e236bc0117fe0512cc254/lmpm/lmpm_model.py#L309-L310) being just one of them.

**Comment by wwyy1234** [comment]
> During the training, in the part of backbone, I got this error:
> 
> File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 694, in forward value = value.reshape(B, self.num_heads, self.value_channels//self.num_heads, n_l) RuntimeError: shape '[24, 1, 96, 40]' is invalid for input of size 368640
> 
> this happened in the part of SpatialImageLanguageAttention, I found num_heads is 1, so this is not a MultiheadAttention right? but I don't know whether the shape or the size is wrong, so what is the expected shape or size?
> 
> and the full error message is below: Traceback (most recent call last): File "train_net_lmpm.py", line 318, in launch( File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 69, in launch mp.start_processes( File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes while not context.join(): File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join raise ProcessRaisedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 1 terminated with the following error: Traceback (most recent call last): File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker main_func(*args) File "/root/MeViS/train_net_lmpm.py", line 312, in main return trainer.train() File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train super().train(self.start_iter, self.max_iter) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 155, in train self.run_step() File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 494, in run_step self._trainer.run_step() File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 494, in run_step loss_dict = self.model(data) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward output = self.module(*inputs[0], **kwargs[0]) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/MeViS/lmpm/lmpm_model.py", line 281, in forward return self.train_model(batched_inputs) File "/root/MeViS/lmpm/lmpm_model.py", line 312, in train_model features = self.backbone(images.tensor, lang_feat_sentence, lang_mask) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 785, in forward y = super().forward(x, l, l_mask) File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 470, in forward x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww, l, l_mask) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 590, in forward x_residual = self.fusion(x, l, l_mask) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(_input, **kwargs) File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 627, in forward lang = self.image_lang_att(x, l, l_mask) # (B, H_W, dim) File "/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/MeViS/mask2former/modeling/backbone/swin.py", line 694, in forward value = value.reshape(B, self.num_heads, self.value_channels//self.num_heads, n_l) RuntimeError: shape '[24, 1, 96, 40]' is invalid for input of size 368640

Excuse me, have you solved this problem? I encountered the same issue. I'm using two GPUs. Could you please let me know how you resolved it?

**Comment by Starboy-at-earth** [comment]
same problem encountered....

**Comment by ksk2023** [comment]
> 遇到同样的问题....

您好，请问您解决您的问题了吗？

**Comment by ksk2023** [comment]
> > 在训练过程中，在主干部分，我得到了这个错误：
> > 文件“/root/MeViS/mask2former/modeling/backbone/swin.py”，第 694 行，前向值 = value.reshape(B, self.num_heads, self.value_channels//self.num_heads, n_l) RuntimeError: shape ' [24, 1, 96, 40]' 对于大小为 368640 的输入无效
> > 这发生在 SpatialImageLanguageAttention 部分，我发现 num_heads 是 1，所以这不是 MultiheadAttention 对吗？但不知道形状或尺寸是否错误，那么期望的形状或尺寸是多少？
> > 完整的错误消息如下：Traceback（最近一次调用最后）：文件“train_net_lmpm.py”，第318行，在启动（文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/” detectorron2/engine/launch.py​​”，第 69 行，在启动 mp.start_processes( 文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py”，第 188 行，在 start_processes 中，而不是 context.join()：文件“/root/anaconda3/envs /torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py”，第 150 行，在 join 中引发 ProcessRaishedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaishedException:
> > -- 进程 1 因以下错误而终止：Traceback（最近一次调用最后一次）：文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py”，第 59 行，在 _wrap fn(i, *args) 文件中“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/launch.py​​”，第 123 行，在 _distributed_worker main_func(*args) 文件“/root/MeViS/train_net_lmpm.py”中，第312行，在主返回trainer.train()文件中“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py”，第 484 行，在 train super().train(self.start_iter, self.max_iter) 文件中“ /root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py”，第 155 行，在火车中self.run_step() 文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/defaults.py”，第 494 行，在 run_step self._trainer.run_step() 文件“/ root/anaconda3/envs/torch1/lib/python3.8/site-packages/detectron2/engine/train_loop.py”，第 494 行，在run_step loss_dict = self.model(data) 文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1102 行，在 _call_impl 返回forward_call(*输入，**kwargs）文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py”，第 886 行，前向输出 = self.module(*inputs[0], ** kwargs[0]）文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，行1102，在_call_impl中返回forward_call(*input, **kwargs)文件“/root/MeViS/lmpm/lmpm_model.py”，第281行，在forward中返回self.train_model(batched_inputs)文件“/root/MeViS/lmpm/lmpm_model .py”，第 312 行，在 train_model features = self.backbone(images.tensor, lang_feat_sentence, lang_mask) 文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1102 行，在 _call_impl 返回forward_call(*input, **kwargs) 文件“/root/MeViS/mask2former/modeling/backbone/swin.py”，第785行，在forward y = super().forward(x, l, l_mask)文件中“/root/MeViS/mask2former/modeling/backbone/swin.py”，第 470 行，前向 x_out，H，W，x，Wh，Ww = 层（x，Wh，Ww，l，l_mask） 文件“/root /anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1102 行，在_call_impl 返回forward_call(*input, **kwargs) 文件“/root/MeViS/mask2former/modeling/backbone/swin.py”，第 590 行，向前 x_residual = self.fusion(x, l, l_mask) 文件“/root /anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，行1102、在_call_impl中返回forward_call(_input, **kwargs) 文件“/root/MeViS/mask2former/modeling/backbone/swin.py”，第627行，在forward lang = self.image_lang_att(x, l, l_mask) # ( B、H_W、暗淡）文件“/root/anaconda3/envs/torch1/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1102 行，在 _call_impl 返回forward_call(*input, **kwargs) 文件“/root /MeViS/mask2former/modeling/backbone/swin.py”，第 694 行，前向值 = value.reshape(B, self.num_heads, self.value_channels//self.value_channelsnum_heads, n_l) RuntimeError: 形状 '[24, 1, 96, 40]' 对于大小为 368640 的输入无效
> 
> 请问您这个问题解决了吗？我遇到了同样的问题。我正在使用两个 GPU。您能告诉我您是如何解决的吗？

您好，请问您解决您的问题了吗？
